[firebase]
type = "service_account"
project_id = "akillisutakip"
private_key_id = "3de4b6982e75e1ad8795bf321d640ff02bcfa090"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDZ8WYgeGiYBLui
kmJm86ppYCpc6Qq+NTrQqjBh6lF/YUzYkALJzZfZCcMTFUsTIdmmrP4NdWGywqBF
MdFUyEokgMLDqGyCc9XNgE02qEnQnEdL5JfFvupiMl0Xn3xpacGwd6aLCZexuTtl
nCVmLEAhHY2BKas5XpTQxvCNWKpNjF41z1unSGR94UAf8BF/ZJluGbUjOStG6XbY
cnKEoHA8aNV7x6181LM6G6UauClH1Crs2msxBxnZ3zeghAuPEi2tOWrsCQpEqEES
0uHLm4W/YBlxW1YgpIFzwdvrWOncMi/itookFSlSdeFBlqiYlHIXWWzTGQYAB/Ug
r5iXR7EHAgMBAAECggEAAkcrL9xfWtnujrSDwvSInCrqQlkG8/yXfk98P6EC+4zU
WtTxZmzMoBDLQOaomW0SayxnANcUQ66FREPi1zaFtD4WfC8VtceXOMCm96HVNpES
3QFvGXk1U0mAei2nAj2GCWUf4qrIXIIvOL1g1f9i8aeHFiAlo/X5k2psohynpBHG
n/zjh/9YmmeWasDvGOYJxc3vd0Nj1EJDckGW6BaLrLtc1BTLQuR/6nJNAE3Mgpcl
t34keuJdCa2LjKFyvZFmVE+lHj5REzct/pqmhwFGRY1QVfXMEG7MUXMoqqNof3YQ
C7ITwNEUQZPwLVCdtROiFpTEgd+/iSaqQb95ty3hvQKBgQD0tXtsP6gaHIGG6NCj
3uDxuM/WgXb0kwQKqYf4YmwgdecSaOMHAZ9VUX+Qc9+uLI6j+HjyGfwN4B6x4bzV
H4QwE7lYMKvnl6aWHlH5ssJMsSTZEdiJ2s2KVZ/o0vRC/i7WBkSw7GjAwDEhrltz
nnlfYhMF6aPNBeqMpUrFzONCbQKBgQDj/8FxvVTK7XjqgnnXVq0qNP3IVaTYxlj1
frMda55L87H5lV/U0C78PbXBm8Yn3ZxDJYm1t7iwWPZTl8YG0whO36a1sBTBJUG0
Dqcmf1Rb45rCsX8PdLAyO6W8l1Qt26lHSqzvwQU3kr9vrvR2Q1gGmpqUxQZn7Lz2
gmLLbY14wwKBgHlZIapNatv/9M9k1knc9WmI/y/dJZMk8GUlKrMmg34ZWYwMjUBl
MpEJiBunCm4B1H5FchyEfDSZRj9ptM1vAosgzNGJ2UVQM6DPylDrr2R+l8o5Ckta
QIDv8wtuyQgLqkgh9aBSq6Oh6vtLzjfoX5XYOZy9/qdl3qj+MrUh5DSFAoGAM1wK
jH+U2T2TTmhi/ODWkzpqrLU2NCrCIVMQMCFtADj+L3XJp5vZ6bJQ/jMD+Tj/mVSc
Z9XiAb+YhY4b6q+hIHtbB3SJyFSHL3NZjd+C9kwYMaFgOPAVPMuY8xm3ubjQsiGN
QVjevv0MqLDlmrpi2uH6zmZvoft/OZx3etHL25cCgYBbuDDwzpu2FD13SGgsxiQD
B9hp2Miurq4+XcwUKF2WTjwW8SvGUOMJTh+zEY8CHZP8QQ2B2NAf4LqMMGCAg/wT
0T/hvpGImuvDZJ9OjyuIrUCQqxO9XwBOA8DRGEoFJzKtTgPTZdvTX588ehly0TeB
L0M6d74yeh71vmysOlUNQQ==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@akillisutakip.iam.gserviceaccount.com"
client_id = "107227992798333737422"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40akillisutakip.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
